name: Testing
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  short:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
          - 12
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    name: Node.js v${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf true
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.0.0
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run unit tests
        run: pnpm bench
        env:
          FORCE_COLOR: 2
